# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # ---------- Dummy environment variables ----------
    # Replace these with real values (prefer GitHub Secrets) if/when needed.
    env:
      NEXT_PUBLIC_API_URL: "https://dummy.invalid"
      API_SECRET_KEY: "dummy-secret"
      DATABASE_URL: "postgres://user:pass@localhost:5432/dummydb"  # remove if not used
    # -------------------------------------------------

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
